-- ============================================
-- SNOWFLAKE ACCOUNT_USAGE SCHEMA VERIFICATION
-- Run these queries in your Snowflake account to see actual column names
-- ============================================

-- 1. List all columns in TABLE_STORAGE_METRICS
SELECT 
  COLUMN_NAME,
  DATA_TYPE,
  ORDINAL_POSITION
FROM SNOWFLAKE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME = 'TABLE_STORAGE_METRICS'
ORDER BY ORDINAL_POSITION;

-- 2. List all columns in WAREHOUSE_METERING_HISTORY
SELECT 
  COLUMN_NAME,
  DATA_TYPE,
  ORDINAL_POSITION
FROM SNOWFLAKE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME = 'WAREHOUSE_METERING_HISTORY'
ORDER BY ORDINAL_POSITION;

-- 3. List all columns in QUERY_HISTORY
SELECT 
  COLUMN_NAME,
  DATA_TYPE,
  ORDINAL_POSITION
FROM SNOWFLAKE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME = 'QUERY_HISTORY'
ORDER BY ORDINAL_POSITION;

-- 4. List all columns in STORAGE_USAGE
SELECT 
  COLUMN_NAME,
  DATA_TYPE,
  ORDINAL_POSITION
FROM SNOWFLAKE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME = 'STORAGE_USAGE'
ORDER BY ORDINAL_POSITION;

-- 5. Sample data from TABLE_STORAGE_METRICS (see actual column values)
SELECT TOP 1 *
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
WHERE DELETED = FALSE 
  AND ACTIVE_BYTES > 0;

-- 6. Sample data from WAREHOUSE_METERING_HISTORY
SELECT TOP 1 *
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(day, -7, CURRENT_TIMESTAMP());

-- 7. Sample data from QUERY_HISTORY
SELECT TOP 1 *
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(day, -1, CURRENT_TIMESTAMP());

-- 8. Sample data from STORAGE_USAGE
SELECT TOP 1 *
FROM SNOWFLAKE.ACCOUNT_USAGE.STORAGE_USAGE
WHERE USAGE_DATE >= DATEADD(day, -7, CURRENT_DATE());

-- ============================================
-- VERIFY SPECIFIC COLUMNS WE NEED
-- ============================================

-- 9. Check if CREDITS_USED_COMPUTE exists in QUERY_HISTORY (should be EMPTY)
SELECT 
  COLUMN_NAME
FROM SNOWFLAKE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME = 'QUERY_HISTORY'
  AND COLUMN_NAME = 'CREDITS_USED_COMPUTE';
-- Expected: No rows (column doesn't exist)

-- 10. Check if CREDITS_USED_COMPUTE exists in WAREHOUSE_METERING_HISTORY (should return 1 row)
SELECT 
  COLUMN_NAME
FROM SNOWFLAKE.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'ACCOUNT_USAGE'
  AND TABLE_NAME = 'WAREHOUSE_METERING_HISTORY'
  AND COLUMN_NAME = 'CREDITS_USED_COMPUTE';
-- Expected: 1 row with CREDITS_USED_COMPUTE

-- ============================================
-- TEST ACTUAL QUERIES WE USE
-- ============================================

-- 11. Test cost metrics query (from extractCostMetrics)
SELECT 
  COALESCE(SUM(CREDITS_USED_COMPUTE + CREDITS_USED_CLOUD_SERVICES), 0) AS TOTAL_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP());

-- 12. Test storage query (from extractStorageData)
SELECT 
  TABLE_CATALOG,
  TABLE_SCHEMA,
  TABLE_NAME,
  ACTIVE_BYTES,
  TIME_TRAVEL_BYTES,
  FAILSAFE_BYTES,
  RETAINED_FOR_CLONE_BYTES,
  IS_TRANSIENT,
  TABLE_CREATED,
  TABLE_DROPPED
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
WHERE DELETED = FALSE
  AND ACTIVE_BYTES > 0
  AND TABLE_CATALOG IS NOT NULL
  AND TABLE_SCHEMA IS NOT NULL
  AND TABLE_NAME IS NOT NULL
ORDER BY ACTIVE_BYTES DESC
LIMIT 10;

-- 13. Test warehouse metrics query (NEW VERSION)
WITH query_stats AS (
  SELECT 
    WAREHOUSE_NAME,
    COUNT(*) AS TOTAL_QUERIES,
    SUM(TOTAL_ELAPSED_TIME) AS TOTAL_EXECUTION_TIME_MS
  FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
  WHERE START_TIME >= DATEADD(day, -7, CURRENT_TIMESTAMP())
    AND WAREHOUSE_NAME IS NOT NULL
  GROUP BY WAREHOUSE_NAME
),
credit_usage AS (
  SELECT DISTINCT
    WAREHOUSE_NAME,
    SUM(CREDITS_USED_COMPUTE + CREDITS_USED_CLOUD_SERVICES) 
      OVER (PARTITION BY WAREHOUSE_NAME) AS CREDITS_USED,
    FIRST_VALUE(WAREHOUSE_SIZE) 
      OVER (PARTITION BY WAREHOUSE_NAME ORDER BY START_TIME DESC) AS WAREHOUSE_SIZE
  FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
  WHERE START_TIME >= DATEADD(day, -7, CURRENT_TIMESTAMP())
)
SELECT 
  COALESCE(qs.WAREHOUSE_NAME, cu.WAREHOUSE_NAME) AS WAREHOUSE_NAME,
  COALESCE(qs.TOTAL_QUERIES, 0) AS TOTAL_QUERIES,
  COALESCE(qs.TOTAL_EXECUTION_TIME_MS, 0) AS TOTAL_EXECUTION_TIME_MS,
  COALESCE(cu.CREDITS_USED, 0) AS CREDITS_USED,
  NULL AS UTILIZATION_PERCENT,
  cu.WAREHOUSE_SIZE
FROM query_stats qs
FULL OUTER JOIN credit_usage cu ON qs.WAREHOUSE_NAME = cu.WAREHOUSE_NAME;

-- ============================================
-- COLUMN NAME CASE CHECK
-- ============================================

-- 14. Verify column names are returned in UPPERCASE
-- Run this and look at the column headers in the result
SELECT 
  TABLE_CATALOG as check_if_uppercase,
  table_catalog as check_if_lowercase
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
LIMIT 1;
-- Both aliases should work, but the actual column name from Snowflake is UPPERCASE
