-- Create the repository_analysis_settings table to store custom prompts for analysis
-- This stores organization-level settings that apply to all users of a repository
CREATE TABLE IF NOT EXISTS code_insights.repository_analysis_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repository_full_name TEXT NOT NULL UNIQUE, -- e.g., 'owner/repo' - matches files table
    business_overview TEXT,
    naming_standards TEXT,
    language VARCHAR(50) NOT NULL,
    created_by UUID REFERENCES auth.users(id), -- Admin who created the settings
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add helpful comments
COMMENT ON TABLE code_insights.repository_analysis_settings IS 'Organization-level analysis settings that apply to all users processing files from a repository';
COMMENT ON COLUMN code_insights.repository_analysis_settings.repository_full_name IS 'Full repository name in format owner/repo, matches the files table';
COMMENT ON COLUMN code_insights.repository_analysis_settings.business_overview IS 'Custom business context for LLM analysis';
COMMENT ON COLUMN code_insights.repository_analysis_settings.naming_standards IS 'Custom naming conventions and coding standards';
COMMENT ON COLUMN code_insights.repository_analysis_settings.language IS 'Primary technology stack for optimized analysis';
COMMENT ON COLUMN code_insights.repository_analysis_settings.created_by IS 'User who created these organization settings';

-- Add row-level security
ALTER TABLE code_insights.repository_analysis_settings ENABLE ROW LEVEL SECURITY;

-- Grant permissions to service_role for backend operations
GRANT ALL PRIVILEGES ON TABLE code_insights.repository_analysis_settings TO service_role;
GRANT ALL PRIVILEGES ON TABLE code_insights.repository_analysis_settings TO postgres;

-- Policy: Allow service_role full access (for backend API operations)
CREATE POLICY "Allow service_role full access to repository settings"
ON code_insights.repository_analysis_settings
FOR ALL
TO service_role
USING (true);

-- Policy: Allow authenticated users to read settings for repositories they have access to
CREATE POLICY "Allow users to read repository settings they have access to"
ON code_insights.repository_analysis_settings
FOR SELECT
TO authenticated
USING (
    repository_full_name IN (
        SELECT DISTINCT repository_full_name 
        FROM code_insights.files 
        WHERE user_id = auth.uid()
    )
);

-- Policy: Allow users to manage settings for repositories they have processed
-- (This assumes the user who first processes a repo can set its organization settings)
CREATE POLICY "Allow users to manage settings for their repositories"
ON code_insights.repository_analysis_settings
FOR ALL
TO authenticated
USING (
    created_by = auth.uid() OR
    repository_full_name IN (
        SELECT DISTINCT repository_full_name 
        FROM code_insights.files 
        WHERE user_id = auth.uid()
    )
);

-- Create index for performance
CREATE INDEX idx_repository_analysis_settings_repo_name 
ON code_insights.repository_analysis_settings(repository_full_name);

-- Enable the moddatetime extension if not already enabled
CREATE EXTENSION IF NOT EXISTS moddatetime SCHEMA extensions;

-- Trigger to update 'updated_at' timestamp
CREATE TRIGGER handle_updated_at
BEFORE UPDATE ON code_insights.repository_analysis_settings
FOR EACH ROW
EXECUTE PROCEDURE extensions.moddatetime(updated_at); 