CREATE TABLE IF NOT EXISTS github_module.github_installation_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state TEXT NOT NULL UNIQUE,
    supabase_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add a comment to the table
COMMENT ON TABLE github_module.github_installation_states IS 'Stores temporary state values for linking GitHub App installations to users.';

-- Enable RLS
ALTER TABLE github_module.github_installation_states ENABLE ROW LEVEL SECURITY;

-- Create policies
-- Users can only manage their own state records.
CREATE POLICY "Allow individual user access to their own states" 
ON github_module.github_installation_states
FOR ALL
USING (auth.uid() = supabase_user_id)
WITH CHECK (auth.uid() = supabase_user_id);

-- Add an index on the state column for faster lookups
CREATE INDEX IF NOT EXISTS idx_github_installation_states_on_state ON github_module.github_installation_states(state);

-- Add an index on created_at for potential cleanup jobs
CREATE INDEX IF NOT EXISTS idx_github_installation_states_on_created_at ON github_module.github_installation_states(created_at);

-- Grant permissions
-- The service_role (used by backend admin client) needs full access.
-- This role bypasses RLS by default, but explicit grants are good practice and sometimes necessary.
GRANT ALL ON TABLE github_module.github_installation_states TO service_role;

-- Authenticated users might need to select their own states (covered by RLS policy)
-- but explicit SELECT grant can be added if needed beyond RLS.
GRANT SELECT ON TABLE github_module.github_installation_states TO authenticated;

-- For INSERT, UPDATE, DELETE, the RLS policy "Allow individual user access to their own states"
-- already defines the conditions. If authenticated users need to insert directly (not via service_role),
-- the RLS policy handles it.
-- If you want authenticated users to be able to insert directly into this table (which they are, as per the RLS policy)
-- you also need to grant them INSERT at the table level.
GRANT INSERT (state, supabase_user_id) ON TABLE github_module.github_installation_states TO authenticated;
-- Note: Granting UPDATE/DELETE to 'authenticated' would also be restricted by RLS.

-- Make sure the sequence for the ID is also usable by roles that can insert.
GRANT USAGE, SELECT ON SEQUENCE github_module.github_installation_states_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE github_module.github_installation_states_id_seq TO authenticated;
