-- 1. Create a new schema for our GitHub integration data
CREATE SCHEMA IF NOT EXISTS github_module;

-- 2. Grant usage permissions on the new schema to relevant roles
GRANT USAGE ON SCHEMA github_module TO postgres, service_role, authenticated, anon;

-- 3. Create the table to store GitHub App installation details
CREATE TABLE IF NOT EXISTS github_module.github_app_installations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    installation_id BIGINT NOT NULL UNIQUE,
    app_id BIGINT NOT NULL,
    target_id BIGINT NOT NULL,
    target_type TEXT NOT NULL,
    target_login TEXT NOT NULL,
    target_avatar_url TEXT,
    repository_selection TEXT NOT NULL,
    supabase_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    permissions JSONB,
    events TEXT[],
    suspended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON COLUMN github_module.github_app_installations.installation_id IS 'The unique ID for the installation provided by GitHub.';
COMMENT ON COLUMN github_module.github_app_installations.target_id IS 'The GitHub user or organization ID where the app is installed.';
COMMENT ON COLUMN github_module.github_app_installations.supabase_user_id IS 'The user in our application who initiated the installation.';
COMMENT ON COLUMN github_module.github_app_installations.repository_selection IS 'Which repositories the installation can access (e.g., "all" or "selected").';

-- 4. Create a table to store the specific repositories an installation can access
CREATE TABLE IF NOT EXISTS github_module.github_installation_accessible_repos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    installation_table_id BIGINT NOT NULL REFERENCES github_module.github_app_installations(id) ON DELETE CASCADE,
    repo_id BIGINT NOT NULL,
    node_id TEXT,
    name TEXT NOT NULL,
    full_name TEXT NOT NULL,
    private BOOLEAN NOT NULL,
    html_url TEXT,
    description TEXT,
    default_branch TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (installation_table_id, repo_id)
);

COMMENT ON COLUMN github_module.github_installation_accessible_repos.installation_table_id IS 'A foreign key reference to our github_app_installations table.';
COMMENT ON COLUMN github_module.github_installation_accessible_repos.full_name IS 'The full name of the repository, e.g., "owner/repo".';

-- 5. Set default privileges for the service_role on the new tables
ALTER TABLE github_module.github_app_installations ENABLE ROW LEVEL SECURITY;
ALTER TABLE github_module.github_installation_accessible_repos ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE github_module.github_app_installations TO service_role;
GRANT ALL ON TABLE github_module.github_installation_accessible_repos TO service_role;
GRANT ALL ON SEQUENCE github_module.github_app_installations_id_seq TO service_role;
GRANT ALL ON SEQUENCE github_module.github_installation_accessible_repos_id_seq TO service_role;